export const applicationData = [
  {
    title: "Beverages & ",
    highlight: "Breweries",
    image: "/assets/img/Applications/1.jpeg",
    content: `We supply beverage-grade CO2 for carbonation, ensuring fizz, taste, and product integrity. Our CO2 meets international quality standards, making it ideal for breweries and soft drink manufacturers.`,
    imageFirst: true,
  },
  {
    title: "MIG & ",
    highlight: "Welding",
    image: "/assets/img/Applications/2.jpeg",
    content: `Our high-purity CO2 is extensively used as a shielding gas in Metal Inert Gas (MIG) and MAG welding processes. It creates an inert atmosphere by displacing oxygen around the welding arc, which enhances weld integrity, reduces oxidation, minimizes spatter, and results in a cleaner, stronger weld bead. Industries such as automotive and heavy machinery rely on our CO2 to improve welding performance, reduce material wastage, and increase productivity.`,
    imageFirst: false,
  },
  {
    title: "Airline ",
    highlight: "Catering",
    image: "/assets/img/Applications/3.jpeg",
    content: `In airline catering, maintaining food quality during transit is critical. Rajgir Cryogenic Gases LLP provides high-purity dry ice that keeps meals fresh and hygienic without the need for electricity. Stored in insulated containers within trolleys, dry ice sublimates into gas without leaving moisture or residue, making it ideal for in-flight meal service and international catering logistics.`,
    imageFirst: true,
  },
  {
    title: "Food ",
    highlight: "Processingg",
    image: "/assets/img/Applications/4.jpeg",
    content: `Rajgir’s CO2 and dry ice solutions play a vital role in food processing operations including chilling, freezing, packaging, and transport. Liquid CO2 provides rapid cooling while preserving texture, color, and nutritional value. Dry ice is used for quick freezing and controlled atmosphere packaging. Our offerings help reduce microbial activity, extend shelf life, and support hygienic standards across the food industry.`,
    imageFirst: false,
  },
  {
    title: "Dry Ice ",
    highlight: "Blasting",
    image: "/assets/img/Applications/5.jpeg",
    content: `Dry Ice Blasting is a revolutionary industrial cleaning method using high-speed dry ice pellets. Upon impact, the pellets sublimate, lifting contaminants without damaging underlying surfaces. This non-abrasive, residue-free process is ideal for precision cleaning in food production, automotive, electrical equipment, and sensitive machinery. Rajgir supplies dry ice in various grades tailored to your cleaning requirements.`,
    imageFirst: true,
  },
  {
    title: "Fire ",
    highlight: "Extinguishers",
    image: "/assets/img/Applications/6.jpeg",
    content: `Carbon dioxide is a key agent in fire suppression systems, especially for electrical and flammable liquid fires. Our CO2 extinguishes fire by displacing oxygen and cooling the area, without leaving any residue. It is commonly used in data centers, laboratories, and industrial facilities where clean extinguishing is critical. Rajgir supplies high-purity CO2 that meets fire safety standards for maximum reliability.`,
    imageFirst: false,
  },
  {
    title: "",
    highlight: "Foundry",
    image: "/assets/img/Applications/7.jpeg",
    content: `CO2 is used in the foundry industry for curing sodium silicate sand molds. When CO2 gas is passed through the mold mixture, it reacts with the sodium silicate to create a hard, solid structure. This process offers improved dimensional accuracy and mold strength. Rajgir’s CO2 enables faster mold production with lower environmental impact and reduced energy requirements.`,
    imageFirst: true,
  },
  {
    title: "Effluent ",
    highlight: "Treatments",
    image: "/assets/img/Applications/8.jpeg",
    content: `Rajgir's CO2 solutions help regulate pH levels in industrial wastewater treatment systems. As a mild acid, CO2 safely lowers alkalinity without the risks associated with mineral acids. It reduces corrosion, prevents scaling, and is safer for operators and the environment. This method is widely adopted in chemical, textile, and food processing industries for sustainable effluent management.`,
    imageFirst: false,
  },
  {
    title: "Pharmaceuticals ",
    highlight: "",
    image: "/assets/img/Applications/9.jpeg",
    content: `Dry ice is indispensable in pharmaceutical logistics for maintaining cold chain integrity. Rajgir produces high-purity dry ice used for vaccine preservation, clinical samples, and other temperature-sensitive medicines. Our dry ice sublimates without melting, ensuring contamination-free storage and transport. It's trusted by pharmaceutical companies, laboratories, and hospitals across the country.`,
    imageFirst: true,
  },
  {
    title: "Ice ",
    highlight: "Creams",
    image: "/assets/img/Applications/10.jpeg",
    content: `For ice cream transportation and storage, dry ice is a superior solution to mechanical refrigeration. It maintains ultra-low temperatures, extends product shelf life, and eliminates the need for electrical power. Rajgir supplies high-density dry ice blocks and pellets that are safe, clean, and efficient for ice cream manufacturers and distributors nationwide.`,
    imageFirst: false,
  },
  {
    title: "Floriculture ",
    highlight: "",
    image: "/assets/img/Applications/11.jpeg",
    content: `CO2 is used in greenhouse and controlled environment agriculture to stimulate plant growth. By enriching the air with carbon dioxide, photosynthesis is accelerated, resulting in faster growth, improved yield, and healthier plants. Rajgir provides precise CO2 delivery systems for floriculture businesses seeking consistent, high-quality plant production.`,
    imageFirst: true,
  },
  {
    title: "Fruits & ",
    highlight: "Vegetables",
    image: "/assets/img/Applications/12.jpeg",
    content: `Dry ice is widely used to preserve fruits and vegetables during transit. Its ultra-cold temperature and sublimation properties allow for moisture-free cooling that keeps produce fresh, extends shelf life, and reduces spoilage. Rajgir supplies food-grade dry ice suitable for logistics chains serving farms, cold stores, and retail chains.`,
    imageFirst: false,
  },
  {
    title: "",
    highlight: "Fertilizers",
    image: "/assets/img/Applications/13.jpeg",
    content: `Rajgir supplies carbon dioxide for urea manufacturing in fertilizer plants. CO2 reacts with ammonia to form urea, a vital nitrogen-based fertilizer. By providing additional CO2, fertilizer plants can enhance production capacity. Our high-purity CO2 helps maintain process efficiency, quality, and environmental compliance.`,
    imageFirst: true,
  },
];
